apiVersion: v1
kind: Pod
metadata:
  name: mysql-flask-pod
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '1234'
      ports:
        - containerPort: 3306
    - name: flask-app
      image: taeahmed/simple_flask_app:latest
      ports:
        - containerPort: 5000
