apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-flask-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-flask
  template:
    metadata:
      labels:
        app: mysql-flask
      name: mysql-flask-pod
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: '1234'
        ports:
        - containerPort: 3305
      - name: flask-app
        image: taeahmed/simple_flask_app:latest
        ports:
        - containerPort: 5000
